### ISSUE TITLE
security problem

### ISSUE THREAD

**Issue by eijeijfo** [ReikaKalseki/Reika_SubnauticaModsShared#7]
norton keeps saying the mod dll files are a virus so it keeps removing it. is it a virus?

**Comment by ReikaKalseki** [comment]
No, and noone else is having that issue. I suggest you check your system.

...Are you using the official files?

**Comment by eijeijfo** [comment]
reiKA >:[

**Comment by ReikaKalseki** [comment]
That is not a productive response. You were asked a direct question.

**Comment by eijeijfo** [comment]
it said the dll files are dangerous

**Comment by ReikaKalseki** [comment]
Literally nobody else has indicated issues and your first response - and creation of a new issue - has not even convinced me you are not trying some kind of joke (hence the tags I applied above). If you *are* being honest, then you probably have either a crap AV, an infected system, or are downloading some random file rather than the official ones. None of those are my fault or within my power to resolve.
